In [1]:
import numpy as np
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[:,:,np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print (rows)

[1 2 4 5]


In [2]:
import numpy as np
x = np.arange(1,81).reshape(4,5,2,2)
print (x)
print ('-'*50)
print (x[...,1])
print ('-'*50)
print(x[:,1])

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]

  [[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]

  [[17 18]
   [19 20]]]


 [[[21 22]
   [23 24]]

  [[25 26]
   [27 28]]

  [[29 30]
   [31 32]]

  [[33 34]
   [35 36]]

  [[37 38]
   [39 40]]]


 [[[41 42]
   [43 44]]

  [[45 46]
   [47 48]]

  [[49 50]
   [51 52]]

  [[53 54]
   [55 56]]

  [[57 58]
   [59 60]]]


 [[[61 62]
   [63 64]]

  [[65 66]
   [67 68]]

  [[69 70]
   [71 72]]

  [[73 74]
   [75 76]]

  [[77 78]
   [79 80]]]]
--------------------------------------------------
[[[ 2  4]
  [ 6  8]
  [10 12]
  [14 16]
  [18 20]]

 [[22 24]
  [26 28]
  [30 32]
  [34 36]
  [38 40]]

 [[42 44]
  [46 48]
  [50 52]
  [54 56]
  [58 60]]

 [[62 64]
  [66 68]
  [70 72]
  [74 76]
  [78 80]]]
--------------------------------------------------
[[[ 5  6]
  [ 7  8]]

 [[25 26]
  [27 28]]

 [[45 46]
  [47 48]]

 [[65 66]
  [67 68]]]


In [3]:
A = np.random.randint(0,5,(3,2))
print (A [..., np.newaxis])
print (A [..., np.newaxis, np.newaxis])

[[[2]
  [2]]

 [[3]
  [0]]

 [[1]
  [1]]]
[[[[2]]

  [[2]]]


 [[[3]]

  [[0]]]


 [[[1]]

  [[1]]]]


In [4]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2,5],[4,4,5]])
A == B


array([[ True,  True, False],
       [ True, False, False]])

In [5]:
import numpy as np
d2 = np.arange(20).reshape(4,5)
d3 = np.arange(20).reshape(5,4)
print (d2 == d3)
print ('-'*50)
A = np.array([10,7,2,0])
B = np.array([10,9,8,7,6,5,4,3,2,1])
print (A == B)

False
--------------------------------------------------
False


In [6]:
a = np.array([10,7,2,0])
b = np.array([10,9,8,7,6,5,4,3,2,1])
print (a == b)
print ('-'*50)
c = a [...,np.newaxis]
print (c == b)

False
--------------------------------------------------
[[ True False False False False False False False False False]
 [False False False  True False False False False False False]
 [False False False False False False False False  True False]
 [False False False False False False False False False False]]


In [7]:
import numpy as np
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[:,:,np.newaxis, np.newaxis] == B)

print (C)

[[[[False False]
   [ True False]]

  [[False False]
   [False False]]

  [[False  True]
   [False False]]]


 [[[False False]
   [False False]]

  [[False False]
   [False False]]

  [[False False]
   [False False]]]


 [[[False  True]
   [False False]]

  [[False False]
   [False False]]

  [[False False]
   [False False]]]


 [[[False False]
   [False False]]

  [[False False]
   [False False]]

  [[False False]
   [False False]]]


 [[[ True False]
   [False  True]]

  [[False  True]
   [False False]]

  [[False  True]
   [False False]]]


 [[[False False]
   [False False]]

  [[False False]
   [False False]]

  [[ True False]
   [False  True]]]


 [[[False  True]
   [False False]]

  [[ True False]
   [False  True]]

  [[ True False]
   [False  True]]]


 [[[False False]
   [False False]]

  [[False False]
   [False False]]

  [[False False]
   [False False]]]]


In [8]:
import numpy as np

A = np.array([10,7,2,0])
B = np.array([10,9,8,7,6,5,4,3,2,1])
print (A == B)
print ('-'*50)
C = A [...,np.newaxis] == B
print (C)
print ('C location'+'-'*50)
print (np.where(C))
print ('Axis 1 combine'+'-'*50)
print (np.where(C.any(1)))
print ('Axis 0 combine'+'-'*50)
print (np.where(C.any(0)))
print ('-'*50)
print (np.where(C.any((1,0))))

False
--------------------------------------------------
[[ True False False False False False False False False False]
 [False False False  True False False False False False False]
 [False False False False False False False False  True False]
 [False False False False False False False False False False]]
C location--------------------------------------------------
(array([0, 1, 2], dtype=int64), array([0, 3, 8], dtype=int64))
Axis 1 combine--------------------------------------------------
(array([0, 1, 2], dtype=int64),)
Axis 0 combine--------------------------------------------------
(array([0, 3, 8], dtype=int64),)
--------------------------------------------------
(array([0], dtype=int64),)


In [9]:
import numpy as np # 创建一个二维数组
A = np.arange(1,11).reshape(2,5)
print (A,"\n")
sum0 = A.sum(0)
sum1 = A.sum(1)
print("0轴折叠相加\n",sum0)
print("1轴折叠相加\n",sum1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

0轴折叠相加
 [ 7  9 11 13 15]
1轴折叠相加
 [15 40]


In [10]:
import numpy as np
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[:,:,np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print (rows)

[1 4 7]
