In [10]:
import numpy as np
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[:,:,np.newaxis, np.newaxis] == B)
print (A)
print (B)

rows = np.where(C.any((3,1)).all(1))[0]
print ('-'*50)
print (np.where(C))
print ('-'*50)
print (np.where(C.any((3))))
print ('-'*50)
print (np.where(C.any((2))))
print ('-'*50)
print (np.where(C.any((1))))
print ('-'*50)
print (np.where(C.any((3,1))))
print ('-'*50)
print (np.where(C.any((3,1)).all(1)))
print ('-'*50)
print (rows)


[[0 1 4]
 [4 4 0]
 [1 0 4]
 [0 1 2]
 [2 1 1]
 [1 4 2]
 [3 2 3]
 [2 1 2]]
[[1 3]
 [1 4]]
--------------------------------------------------
(array([0, 0, 0, 1, 1, 2, 2, 2, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 7, 7],
      dtype=int64), array([1, 1, 2, 0, 1, 0, 0, 2, 1, 1, 1, 1, 2, 2, 0, 0, 1, 0, 2, 1, 1],
      dtype=int64), array([0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1],
      dtype=int64), array([0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0],
      dtype=int64))
--------------------------------------------------
(array([0, 0, 0, 1, 1, 2, 2, 2, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 7, 7],
      dtype=int64), array([1, 1, 2, 0, 1, 0, 0, 2, 1, 1, 1, 1, 2, 2, 0, 0, 1, 0, 2, 1, 1],
      dtype=int64), array([0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1],
      dtype=int64))
--------------------------------------------------
(array([0, 0, 1, 1, 2, 2, 3, 4, 4, 5, 5, 6, 6, 7], dtype=int64), array([1, 2, 0, 1, 0, 2, 1, 1, 2, 0, 1, 0, 2, 1], dtype